---
title: "Plots"
format:
  html: default
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(stringr)
library(rvest)
library(polite)
library(sf)
library(maps)
library(viridis)
library(leaflet)
library(htmltools)
library(readr)
library(ggplot2)
library(ggthemes)
library(ggrepel)
library(plotly)
```


# Tuition by size

```{r}
mn_college_data |>
  select(size_type, in_state_tuition, public_private) |>
  filter(!is.na(in_state_tuition), in_state_tuition != ".") |>
  group_by(size_type, public_private) |>
  mutate(in_state_tuition = as.numeric(in_state_tuition),
         size_type = as.factor(size_type),
         public_private = as.factor(public_private),
         size_type = fct_recode(size_type, 
                                "< 1,000" = "1",
                                "1,000 - 4,999" = "2",
                                "5,000 - 9,999" = "3",
                                "10,000 - 19,999" = "4",
                                "20,000 +" = "5"),
         public_private = fct_recode(public_private,
                                     "Public" = "1",
                                     "Private (not-for-profit)" = "2",
                                     "Private (for-profit)" = "3")) |>
  summarize(mean_tuition = mean(in_state_tuition)) |>
  ggplot(aes(x = size_type, y = mean_tuition, fill = public_private)) +
  geom_bar(stat = "identity") +
  labs(title = "Average Tuition by Institution Size",
       subtitle = "Colored by Institution Type",
       x = "Size",
       y = "Average Tuition",
       fill = "Type") +
  theme_classic() +
  scale_fill_colorblind()
```
```{r}
mn_college_data |>
  select(in_state_tuition, public_private) |>
  filter(!is.na(in_state_tuition), in_state_tuition != ".") |>
  group_by(public_private) |>
  mutate(in_state_tuition = as.numeric(in_state_tuition),
         public_private = as.factor(public_private),
         public_private = fct_recode(public_private,
                                     "Public" = "1",
                                     "Private (not-for-profit)" = "2",
                                     "Private (for-profit)" = "3")) |>
  summarize(mean_tuition = mean(in_state_tuition)) |>
  ggplot(aes(x = public_private, y = mean_tuition, fill = public_private)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = round(mean_tuition, 1)), vjust = -0.5, size = 3) +
  labs(title = "Average Tuition by Institution Type",
       x = "Type",
       y = "Average Tuition") +
  theme_classic() +
  scale_fill_colorblind(guide = "none") 
```

# Enrollment Vs Student-to-Faculty Ratio

## All schools

```{r}
interactive <- mn_college_data |>
  select(total_enrollment, total_faculty, college_name, public_private) |>
  filter(total_enrollment != "NA",
         total_faculty != "NA") |>
  mutate(student_to_fac = total_enrollment/total_faculty,
         total_enrollment = as.numeric(total_enrollment),
         public_private = as.factor(public_private),
         public_private = fct_recode(public_private,
                                     "Public" = "1",
                                     "Private (not-for-profit)" = "2",
                                     "Private (for-profit)" = "3")) |>
  ggplot(aes(x = total_enrollment, y = student_to_fac)) +
  geom_point(aes(text = college_name, color = public_private)) +
  geom_text_repel(aes(label = college_name)) +
  labs(title = "Total Enrollment Vs. Student-to-faculty Ratio",
       x = "Enrollment",
       y = "Student-to-faculty",
       color = "Institution Type") +
  theme_classic() +
  scale_color_colorblind()

interactive_labels <- ggplotly(interactive)

interactive_labels
```

## Removed Outliers 

```{r}
interactive <- mn_college_data |>
  select(total_enrollment, total_faculty, college_name, public_private) |>
  filter(total_enrollment != "NA",
         total_faculty != "NA") |>
  mutate(student_to_fac = total_enrollment/total_faculty,
         total_enrollment = as.numeric(total_enrollment),
         public_private = as.factor(public_private),
         public_private = fct_recode(public_private,
                                     "Public" = "1",
                                     "Private (not-for-profit)" = "2",
                                     "Private (for-profit)" = "3")) |>
  filter(college_name != c("University of Minnesota-Twin Cities", "Capella University")) |>
  ggplot(aes(x = total_enrollment, y = student_to_fac)) +
  geom_point(aes(text = college_name, color = public_private)) +
  geom_text_repel(aes(label = college_name)) +
  labs(title = "Total Enrollment Vs. Student-to-faculty Ratio",
       x = "Enrollment",
       y = "Student-to-faculty",
       color = "Institution Type") +
  theme_classic() +
  scale_color_colorblind()

interactive_labels <- ggplotly(interactive)

interactive_labels
```

# Athletics 

```{r}
ncaa <- mn_college_data |>
  select(ncaa) |>
  mutate(ncaa = as.factor(ncaa),
         ncaa = fct_recode(ncaa,
                           "NCAA" = "1",
                           "Not NCAA" = "0",
                           "Unknown" = "-1",
                           "Not Applicable" = "-2")) |>
  count(ncaa)

ncaa |>
  ggplot(aes(x = ncaa, y = n, fill = ncaa)) +
  geom_bar(stat = "identity") +
  labs(title = "NCAA Affiliation",
       x = "Affiliation",
       y = "Count") +
  theme_classic() +
  scale_fill_colorblind(guide = "none") 

ncaa_schools <- mn_college_data |>
  select(college_name, ncaa) |>
  filter(ncaa == "1") |>
  select(-ncaa)
  
```

