---
title: "College Data Scraping"
format:
  html: default
editor_options: 
  chunk_output_type: console
---

```{r}
#| include: FALSE

library(tidyverse)
library(stringr)
library(rvest)
library(polite)
library(sf)
library(maps)
library(viridis)
library(leaflet)
library(htmltools)
library(readr)

```

```{r}
#Check if scraping is allowed
robotstxt::paths_allowed("https://www.niche.com/colleges/search/best-colleges/")

session <- bow("https://www.niche.com/colleges/carleton-college/majors/", force = TRUE)

top_majors <- scrape(session) |>
  html_nodes(".popular-entity__name") |>
  html_text()
top_majors
```

```{r}
#A function that takes college names in the correct format (lower case with dashes) 
scrape_majors <- function(college) {
 
    url <- str_c("https://www.niche.com/colleges/", college, "/majors/")
    
    session <- bow(url, force = TRUE)
    
   top_majors <- scrape(session) |>
     html_nodes(".popular-entity__name") |>
     html_text()
    
    tibble(college = college,
           top_majors = top_majors
    )
}

scrape_majors("university-of-minnesota-twin-cities") #U of M example
```

```{r}
#Tibble of college names in the correct format from IPEDS data 
college_data <- read_csv("final_project/data/hd2023 2.csv") |>
  filter(STABBR == "MN") |>
  select(college = INSTNM) 

college_for_majors <- college_data |>
  mutate(college = str_to_lower(college),
         college = str_replace_all(college, "-", " "),
         college = str_replace_all(college, " ", "-"))
```

```{r, include = FALSE}
#Shiny attempt (the goal is to be able to select a college from a drop down and then get a list of the top 10 majors at that school)

titlePanel("")

inputPanel(
  selectInput("college", label = "college name",
    choices = college_for_majors$college)
)

mainPanel(renderPrint({
  scrape_majors <- function(college) {
 
    url <- str_c("https://www.niche.com/colleges/", college, "/majors/")
    
    session <- bow(url, force = TRUE)
    
   top_majors <- scrape(session) |>
     html_nodes(".popular-entity__name") |>
     html_text()
    
    tibble(college = college,
           top_majors = top_majors)
}
}))
```

